// inject-env.js
// Build script to inject Firebase environment variables into env-config.js

const fs = require('fs');

// Get environment variables
const firebaseConfig = {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID
};

// Check if all required variables are set
const requiredVars = ['FIREBASE_API_KEY', 'FIREBASE_PROJECT_ID', 'FIREBASE_APP_ID'];
const missingVars = requiredVars.filter(key => !firebaseConfig[key]);

if (missingVars.length > 0) {
    console.warn(`⚠️  Warning: Missing environment variables: ${missingVars.join(', ')}`);
    console.warn('The app will run in demo mode without cloud storage.');
    console.warn('See ENV_SETUP.md for configuration instructions.');
    process.exit(0); // Don't fail the build, just warn
}

// Generate env-config.js file
const envConfigContent = `
// Auto-generated environment configuration
// DO NOT EDIT THIS FILE MANUALLY
// Generated on: ${new Date().toISOString()}

window.ENV = {
    FIREBASE_API_KEY: "${firebaseConfig.FIREBASE_API_KEY || ''}",
    FIREBASE_AUTH_DOMAIN: "${firebaseConfig.FIREBASE_AUTH_DOMAIN || ''}",
    FIREBASE_PROJECT_ID: "${firebaseConfig.FIREBASE_PROJECT_ID || ''}",
    FIREBASE_STORAGE_BUCKET: "${firebaseConfig.FIREBASE_STORAGE_BUCKET || ''}",
    FIREBASE_MESSAGING_SENDER_ID: "${firebaseConfig.FIREBASE_MESSAGING_SENDER_ID || ''}",
    FIREBASE_APP_ID: "${firebaseConfig.FIREBASE_APP_ID || ''}"
};

console.log('✅ Firebase config loaded from environment variables');
`;

try {
    fs.writeFileSync('env-config.js', envConfigContent);
    console.log('✅ Environment configuration injected successfully!');
    console.log('📝 Created: env-config.js');
    console.log('');
    console.log('Firebase Configuration:');
    console.log(`  Project ID: ${firebaseConfig.FIREBASE_PROJECT_ID || 'NOT SET'}`);
    console.log(`  Auth Domain: ${firebaseConfig.FIREBASE_AUTH_DOMAIN || 'NOT SET'}`);
    console.log(`  API Key: ${firebaseConfig.FIREBASE_API_KEY ? '***' + firebaseConfig.FIREBASE_API_KEY.slice(-4) : 'NOT SET'}`);
} catch (error) {
    console.error('❌ Failed to create env-config.js:', error.message);
    process.exit(1);
}
